BaseURL: "https://periklismant.github.io/"
languageCode: "en-us"
title: "Periklis Mantenoglou"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Periklis Mantenoglou"
  description: The personal webpage of Periklis Mantenoglou
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    #brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableEducation: false
      disableExperience: false
      disablePublications: false
      disableAchievements: false
      disableContact: false

  # About
  about:
    enable: true
    title: "About Me"
    content: |-
      I am an associate researcher in artificial intelligence with a background in electrical and computer engineering.
      I am current working with the <a href="https://cer.iit.demokritos.gr/" target="_blank">Complex Event Recognition group</a> at <a href="https://www.demokritos.gr/" target="_blank">NCSR "Demokritos"</a> in Athens, Greece.
      My research involves stream reasoning, (probabilistic) logic programming and composite event recognition.
      Some additional research areas that I find interesting are\: temporal logics, multi-agent systems and neuro-symbolic AI.
    image: /images/photo.jpg
    name: Periklis Mantenoglou
    position: Research Associate

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - title: "Research Associate"
        #company: 'NCSR "Demokritos"'
        #companyUrl: "https://www.demokritos.gr/"
        date: "2019 - now"
        content: |-
          I am currently working as a research associate with the <a href="https://cer.iit.demokritos.gr/" style="text-decoration:none" target="_blank">Complex Event Recognition group</a> at <a href="https://www.skel.ai" style="text-decoration:none" target="_blank">NCSR "Demokritos"</a>.

      - title: "Intership"
        company: ''
        companyUrl: "https://example.com"
        date: "2018"
        content: |-
          I developed a chess strategy recognition system at the <a href="https://www.skel.ai" style="text-decoration:none" target="_blank">AI lab SKEL</a> of <a href="https://www.skel.ai" style="text-decoration:none" target="_blank">IIT</a>, <a href="https://www.skel.ai" style="text-decoration:none" target="_blank">NCSR "Demokritos"</a>. 
          
          <a href="https://github.com/Periklismant/chess_commentator" style="text-decoration:none" target="_blank" class="button">View the project</a>

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "PhD in Artificial Intelligence"
        school:
          name: "National & Kapodistrian University of Athens"
          url: "https://en.uoa.gr/"
        date: "2019 - 2024"
        content: | 
          <b>Dissertation Title</b>: "Reasoning over Complex Temporal Specifications and Noisy Data Streams" 

          <b>Supervisors</b>:
            - <a href="https://cgi.di.uoa.gr/~takis/" target="_blank">Panagiotis Stamatopoulos</a>
            - <a href="https://users.iit.demokritos.gr/~a.artikis/" target="_blank">Alexander Artikis</a>
            - <a href="https://users.iit.demokritos.gr/~paliourg/" target="_blank">Georgios Paliouras</a>
        #GPA: "3.8 out of 5.0"
        #content: |-
        #Extracurricular Activities
        #- Lorem ipsum dolor sit amet consectetur adipisicing elit.
        #- Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Integrated Master's Degree in Electrical & Computer Engineering"
        school:
          name: "National Technical University of Athens"
          url: "https://www.ntua.gr/en/"
        date: "2014 - 2019"
        content: |
          <b>GPA</b>: 9,04 out of 10  

          <b>Thesis Title</b>: "Online Probabilistic Interval-based Event Calculus"

          <b>Supervisor</b>: <a href="https://www.ece.ntua.gr/en/staff/174" target="_blank">Giorgos Stamou</a>
  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  publications:
    enable: true
    title: "Selected Publications"
    items: 
      - title: "Human-in-the-Loop: Visual Analytics for Building Models Recognizing Behavioral Patterns in Time Series"
        authors:
          - "Natalia V. Andrienko"
          - "Gennady L. Andrienko"
          - "Alexander Artikis"
          - "Periklis Mantenoglou"
          - "Salvatore Rinzivillo"
        venue: "IEEE Computer Graphics and Applications"
        venue_type: "journal"
        acronym: "CG&A"
        volume: "44(3)"
        first_page: "14"
        last_page: "29"
        date: "2024"
        bib: "https://dblp.uni-trier.de/rec/journals/cga/AndrienkoAAMR24.html?view=bibtex"
        doi: "https://doi.org/10.1109/MCG.2024.3379851"
      - title: "Online Event Recognition over Noisy Data Streams"
        selected: "true"
        authors: 
          - "Periklis Mantenoglou"
          - "Alexander Artikis"
          - "Georgios Paliouras"
        venue: "International Journal of Approximate Reasoning"
        venue_type: "journal"
        acronym: "IJAR"
        volume: "161(108993)"
        first_page: "1"
        last_page: "30"
        date: "2023"
        pdf: "https://cer.iit.demokritos.gr/publications/papers/2023/opiec-ijar.pdf"
        code: "https://github.com/Periklismant/oPIEC"
        bib: "https://dblp.org/rec/journals/ijar/MantenoglouAP23.html?view=bibtex"
        doi: "https://doi.org/10.1016/j.ijar.2023.108993"
      - title: "Complex Event Recognition with Allen Relations"
        selected: "true"
        authors: 
          - "Periklis Mantenoglou"
          - "Dimitrios Kelesis"
          - "Alexander Artikis"
        venue: "International Conference on Principles of Knowledge Representation and Reasoning"
        venue_type: "conference"
        acronym: "KR"
        volume: ""
        first_page: "502"
        last_page: "511"
        date: "2023"
        pdf: "https://cer.iit.demokritos.gr/publications/papers/2023/kr_allen.pdf"
        slides: "https://cer.iit.demokritos.gr/publications/slides/2023/rtecallen.pdf"
        code: "https://github.com/aartikis/RTEC/tree/allen"
        bib: "https://dblp.org/rec/conf/kr/MantenoglouKA23.html?view=bibtex"
        doi: "https://doi.org/10.24963/kr.2023/49"
      - title: "Stream Reasoning with Cycles"
        selected: "true"
        authors: 
          - "Periklis Mantenoglou"
          - "Manolis Pitsikalis"
          - "Alexander Artikis"
        venue: "International Conference on Principles of Knowledge Representation and Reasoning"
        venue_type: "conference"
        acronym: "KR"
        volume: ""
        first_page: "533"
        last_page: "553"
        date: "2022"
        pdf: "https://cer.iit.demokritos.gr/publications/papers/2022/KR2022-final.pdf"
        slides: "https://cer.iit.demokritos.gr/publications/slides/2022/mantenoglou-kr22.pdf"
        code: "https://github.com/aartikis/RTEC"
        bib: "https://dblp.org/rec/conf/kr/MantenoglouPA22.html?view=bibtex"
        doi: "https://doi.org/10.24963/kr.2022/56"
      - title: "Online Probabilistic Interval-based Event Calculus"
        selected: "true"
        authors: 
          - "Periklis Mantenoglou"
          - "Alexander Artikis"
          - "Georgios Paliouras"
        venue: "European Conference on Artificial Intelligence"
        venue_type: "conference"
        acronym: "ECAI"
        volume: ""
        first_page: "2624"
        last_page: "2631"
        date: "2020"
        pdf: "https://cer.iit.demokritos.gr/publications/papers/2020/ecai2020.pdf"
        slides: "https://cer.iit.demokritos.gr/publications/slides/2020/ecai_presentation.pdf"
        video: "https://owncloud.skel.iit.demokritos.gr/index.php/s/mezzjWcys4fbnWm"
        code: "https://github.com/Periklismant/oPIEC"
        bib: "https://dblp.uni-trier.de/rec/conf/ecai/MantenoglouAP20.html?view=bibtex"
        doi: "https://doi.org/10.3233/FAIA200399"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    #content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:periklismant1@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
